'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import {
  Toolbar,
  ToolbarHeading,
  ToolbarTitle,
} from '@/components/common/toolbar';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useTranslation } from '@/hooks/useTranslation';
import { isDmsError } from '@/lib/dms/errors';
import { createProject } from '@/lib/dms/mock-store';
import { useDmsActor } from '../../../_lib/use-dms-actor';

/**
 * A SEED, NOT A FORM.
 *
 * ۲-۱ has 46 columns and this page asks for two. The other 43 editable ones
 * belong on the edit page — a create page that grows into the full form is
 * what the convention exists to prevent, and at 46 fields that pressure is
 * real.
 *
 * `projectCode` is absent: ۲-۱ says «تولید خودکار توسط سیستم، یکتا», so the
 * store assigns it and a field here would invent one the API owns.
 */
export function CreateProjectContent() {
  const { t } = useTranslation('dms');
  const router = useRouter();
  const queryClient = useQueryClient();
  const { actor, ready } = useDmsActor();

  const [contractNumber, setContractNumber] = useState('');
  const [contractSubject, setContractSubject] = useState('');

  const isValid =
    contractNumber.trim().length > 0 && contractSubject.trim().length > 0;

  const createMutation = useMutation({
    mutationFn: () => {
      if (!actor) throw new Error('No actor');
      return createProject({ contractNumber, contractSubject, actor });
    },
    onSuccess: (created) => {
      toast.success(
        t('projectCreated', { defaultValue: 'Project created' }) +
          ` — ${created.projectCode}`,
      );
      void queryClient.invalidateQueries({ queryKey: ['dms', 'projects'] });
      router.push(`/admin/projects/edit?id=${created.id}`);
    },
    onError: (error) => {
      toast.error(
        isDmsError(error)
          ? `${error.message} (${error.code})`
          : t('projectCreateFailed', {
              defaultValue: 'The project could not be created.',
            }),
      );
    },
  });

  if (!ready) {
    return (
      <Card>
        <CardContent className="py-8 text-sm text-muted-foreground">
          {t('loading', { defaultValue: 'Loading…' })}
        </CardContent>
      </Card>
    );
  }

  if (!actor || actor.role !== 'ProjectControl') {
    return (
      <div className="[&_div.rounded-xl.bg-card.bg-card]:border-red-500! dark:[&_div.rounded-xl.bg-card.bg-card]:border-red-500!">
        <Card>
          <CardContent className="py-8">
            <h2 className="font-semibold">
              {t('projectControlOnlyTitle', {
                defaultValue: 'This screen belongs to the Project Control role',
              })}
            </h2>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="grid gap-5 lg:gap-7.5">
      <Toolbar>
        <ToolbarHeading>
          <ToolbarTitle>
            {t('newProject', { defaultValue: 'New project' })}
          </ToolbarTitle>
        </ToolbarHeading>
      </Toolbar>

      <Card>
        <CardHeader>
          <CardTitle>
            {t('projectSeedTitle', { defaultValue: 'Basic information' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            {t('projectSeedExplain', {
              defaultValue:
                'Enough to create the record. The contract detail is completed on the next screen. The project code is generated by the system.',
            })}
          </p>

          <div className="space-y-2">
            <label
              className="text-sm font-medium block"
              htmlFor="project-contract-number"
            >
              {t('contractNumber', { defaultValue: 'Contract number' })}{' '}
              <span className="text-destructive">*</span>
            </label>
            <Input
              id="project-contract-number"
              value={contractNumber}
              onChange={(e) => setContractNumber(e.target.value)}
            />
          </div>

          <div className="space-y-2">
            <label
              className="text-sm font-medium block"
              htmlFor="project-contract-subject"
            >
              {t('contractSubject', { defaultValue: 'Contract subject' })}{' '}
              <span className="text-destructive">*</span>
            </label>
            <Input
              id="project-contract-subject"
              value={contractSubject}
              onChange={(e) => setContractSubject(e.target.value)}
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="py-4 flex items-center gap-2">
          <Button
            variant="primary"
            disabled={createMutation.isPending || !isValid}
            onClick={() => createMutation.mutate()}
          >
            {createMutation.isPending
              ? t('creating', { defaultValue: 'Creating…' })
              : t('createProject', { defaultValue: 'Create project' })}
          </Button>
          <Button asChild variant="outline">
            <Link href="/admin/projects">
              {t('cancel', { defaultValue: 'Cancel' })}
            </Link>
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
