'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import {
  Toolbar,
  ToolbarHeading,
  ToolbarTitle,
} from '@/components/common/toolbar';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useTranslation } from '@/hooks/useTranslation';
import { isDmsError } from '@/lib/dms/errors';
import { createVessel } from '@/lib/dms/mock-store';
import { useDmsActor } from '../../../_lib/use-dms-actor';

/**
 * A SEED, NOT A FORM — the estate's create-page rule.
 *
 * ۲-۳ has 22 columns and this page asks for two. The rest belong on the edit
 * page, because a create page that grows into the full form is the thing the
 * convention exists to prevent.
 *
 * `vesselCode` is deliberately absent: ۲-۳ says «تولید خودکار توسط سیستم», so
 * the store assigns it. A field here would invent one the API owns, and the
 * first duplicate would arrive from a user.
 *
 * Single column, one plain card, no numbered badge and no coloured border —
 * per the create-page conventions, badges and colours belong to pages that
 * have more than one section.
 */
export function CreateVesselContent() {
  const { t } = useTranslation('dms');
  const router = useRouter();
  const queryClient = useQueryClient();
  const { actor, ready } = useDmsActor();

  const [name, setName] = useState('');
  const [vesselType, setVesselType] = useState('');

  const isValid = name.trim().length > 0;

  const createMutation = useMutation({
    mutationFn: () => {
      if (!actor) throw new Error('No actor');
      return createVessel({ name, vesselType, actor });
    },
    onSuccess: (created) => {
      toast.success(
        t('vesselCreated', { defaultValue: 'Vessel created' }) +
          ` — ${created.vesselCode}`,
      );
      void queryClient.invalidateQueries({ queryKey: ['dms', 'vessels'] });
      // Hand the new id to the edit page, where the remaining 20 fields live.
      router.push(`/admin/vessels/edit?id=${created.id}`);
    },
    onError: (error) => {
      toast.error(
        isDmsError(error)
          ? `${error.message} (${error.code})`
          : t('vesselCreateFailed', {
              defaultValue: 'The vessel could not be created.',
            }),
      );
    },
  });

  if (!ready) {
    return (
      <Card>
        <CardContent className="py-8 text-sm text-muted-foreground">
          {t('loading', { defaultValue: 'Loading…' })}
        </CardContent>
      </Card>
    );
  }

  if (!actor || actor.role !== 'ProjectControl') {
    return (
      <div className="[&_div.rounded-xl.bg-card.bg-card]:border-red-500! dark:[&_div.rounded-xl.bg-card.bg-card]:border-red-500!">
        <Card>
          <CardContent className="py-8 space-y-2">
            <h2 className="font-semibold">
              {t('projectControlOnlyTitle', {
                defaultValue: 'This screen belongs to the Project Control role',
              })}
            </h2>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="grid gap-5 lg:gap-7.5">
      <Toolbar>
        <ToolbarHeading>
          <ToolbarTitle>
            {t('newVessel', { defaultValue: 'New vessel' })}
          </ToolbarTitle>
        </ToolbarHeading>
      </Toolbar>

      <Card>
        <CardHeader>
          <CardTitle>
            {t('vesselSeedTitle', { defaultValue: 'Basic information' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            {t('vesselSeedExplain', {
              defaultValue:
                'Enough to create the record. The full technical specification is completed on the next screen. The vessel code is generated by the system.',
            })}
          </p>

          <div className="space-y-2">
            <label className="text-sm font-medium block" htmlFor="vessel-name">
              {t('vesselName', { defaultValue: 'Vessel name' })}
              {' '}
              <span className="text-destructive">*</span>
            </label>
            <Input
              id="vessel-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium block" htmlFor="vessel-type">
              {t('vesselType', { defaultValue: 'Vessel type' })}
            </label>
            <Input
              id="vessel-type"
              value={vesselType}
              onChange={(e) => setVesselType(e.target.value)}
              placeholder={t('vesselTypePlaceholder', {
                defaultValue: 'e.g. cutter suction, hopper suction',
              })}
            />
          </div>
        </CardContent>
      </Card>

      {/* Operations card last. */}
      <Card>
        <CardContent className="py-4 flex items-center gap-2">
          <Button
            variant="primary"
            disabled={createMutation.isPending || !isValid}
            onClick={() => createMutation.mutate()}
          >
            {createMutation.isPending
              ? t('creating', { defaultValue: 'Creating…' })
              : t('createVessel', { defaultValue: 'Create vessel' })}
          </Button>
          <Button asChild variant="outline">
            <Link href="/admin/vessels">
              {t('cancel', { defaultValue: 'Cancel' })}
            </Link>
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
